### ISSUE TITLE
Builds on Ubuntu complain about undefined references.

### ISSUE THREAD

**Issue by ulif** [mwarning/device-observatory#14]
Hi @mwarning ,

Thank you for hinting me today to this very interesting project!

On my Ubuntu the `device-observatory` did not compile due to linker problems ("undefined reference"...). This _might_ be caused by the linker option ``--as-needed`` which seems to be enabled by default on Ubuntu. The background is a bit explained here: http://billauer.co.il/blog/2017/04/gcc-ld-link-debian/

The compile problem can be fixed in the `Makefile` by either also setting the linker option `-Wl,--no-as-needed`, or by moving the ``$(LFLAGS)`` expression in the compile line behind the ``$(SRC)`` expression.

As I am not a real C programmer and the fix is only a single line, I did not create a pull request. Please tell, if you would like to have one.

Thanks again for the `device-observatory`

-- ulif

**Comment by mwarning** [comment]
Hi @ulif, yes, that fixed the issue. Thanks for pointing this out!

**Comment by mwarning** [comment]
Btw., in case the Makefile complains about xxd, you may need to install vim-common. It is used to include all html/js/css code into the binary.
